#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# 04a-agw-management-ui.sh — Deploy AgentGateway Enterprise management UI
#
# Installs the `management` Helm chart on cluster1 and wires the AGW data plane
# to emit traces and metrics into the bundled OTel collector + ClickHouse so
# the management UI populates with real traffic data.
#
# What this script installs:
#   - solo-enterprise-ui            (Next.js management console, port 80/4000)
#   - solo-enterprise-telemetry-collector  (OTLP gRPC :4317)
#   - agw-management-clickhouse     (trace + metric storage)
#
# What this script configures:
#   - EnterpriseAgentgatewayParameters/agentgateway-config with rawConfig.config.tracing
#     pointing at the OTel collector, plus per-agent metrics fields
#   - GatewayClass parametersRef binding to the params resource (via helm upgrade)
#   - Restarts AGW data plane so the new tracing config is rendered into the
#     gateway's runtime ConfigMap
#
# Why low CPU requests:
#   t3.medium / small demo nodes don't have headroom for the chart's defaults
#   (700m CPU for solo-enterprise-ui alone). Each container is dropped to 50m
#   CPU which is fine for demo traffic volumes; raise for production.
#
# Run AFTER 02-configure.sh (needs the GatewayClass) and BEFORE 07-register-mcp-servers.sh
# (so traffic generated by registration appears in the UI).
#
# Usage:
#   ./scripts/04a-agw-management-ui.sh
#   AGW_MGMT_VERSION=0.3.12 ./scripts/04a-agw-management-ui.sh
###############################################################################

KUBE_CONTEXT="${KUBE_CONTEXT:-cluster1}"
AGW_NAMESPACE="${AGW_NAMESPACE:-agentgateway-system}"
AGW_MGMT_VERSION="${AGW_MGMT_VERSION:-0.3.12}"
AGW_CHART_VERSION="${AGW_CHART_VERSION:-v2.3.3}"
AGW_MGMT_CHART="${AGW_MGMT_CHART:-oci://us-docker.pkg.dev/solo-public/solo-enterprise-helm/charts/management}"
AGW_CHART="${AGW_CHART:-oci://us-docker.pkg.dev/solo-public/enterprise-agentgateway/charts/enterprise-agentgateway}"

KC="kubectl --context=${KUBE_CONTEXT}"
HELM="helm --kube-context=${KUBE_CONTEXT}"
log() { echo ""; echo "=== $1 ==="; }

###############################################################################
# 1. Install the management chart (UI + collector + ClickHouse)
###############################################################################
log "Installing AGW Enterprise management chart ${AGW_MGMT_VERSION}"

${HELM} upgrade --install agw-management "${AGW_MGMT_CHART}" \
  --namespace "${AGW_NAMESPACE}" \
  --version "${AGW_MGMT_VERSION}" \
  --timeout 10m \
  -f - <<EOF
global:
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
service:
  type: ClusterIP
products:
  kagent:
    enabled: false
  agentgateway:
    enabled: true
    namespace: ${AGW_NAMESPACE}
  mesh:
    enabled: false
  agentregistry:
    enabled: false
clickhouse:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
tracing:
  verbose: true
ui:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
EOF

###############################################################################
# 2. Patch solo-enterprise-ui resource requests
#    The chart's `ui.resources` value above doesn't reach every container in
#    the deployment (the chart only respects it for some). Patch the
#    deployment directly so all four containers fit on a small demo node.
###############################################################################
log "Patching solo-enterprise-ui CPU requests for demo-sized nodes"

# Wait for the deployment object to exist (helm install creates async)
for _ in $(seq 1 30); do
  ${KC} -n "${AGW_NAMESPACE}" get deployment solo-enterprise-ui &>/dev/null && break
  sleep 2
done

# All four containers (ui-frontend, ui-backend, k8sobjects-collector, idp) → 50m
${KC} -n "${AGW_NAMESPACE}" patch deployment solo-enterprise-ui --type=json -p='[
  {"op":"replace","path":"/spec/template/spec/containers/0/resources/requests/cpu","value":"50m"},
  {"op":"replace","path":"/spec/template/spec/containers/1/resources/requests/cpu","value":"50m"},
  {"op":"replace","path":"/spec/template/spec/containers/2/resources/requests/cpu","value":"50m"},
  {"op":"replace","path":"/spec/template/spec/containers/3/resources/requests/cpu","value":"50m"}
]' || echo "  ⚠  Patch failed — continuing (containers may have different layout)."

###############################################################################
# 3. Apply EnterpriseAgentgatewayParameters with tracing + metrics fields
#    Without this, the AGW data plane doesn't emit traces; the collector
#    receives nothing and the UI shows "No data available".
###############################################################################
log "Applying EnterpriseAgentgatewayParameters with OTel tracing config"

${KC} -n "${AGW_NAMESPACE}" apply -f - <<EOF
apiVersion: enterpriseagentgateway.solo.io/v1alpha1
kind: EnterpriseAgentgatewayParameters
metadata:
  name: agentgateway-config
  namespace: ${AGW_NAMESPACE}
spec:
  service:
    spec:
      type: LoadBalancer
  deployment:
    spec:
      replicas: 1
  # Shared extensions: ExtAuth (JWT validation), rate limiter, and ext-cache
  # (Redis for session storage). Without ext-cache, OIDC session-cookie flow
  # fails — Bearer tokens get redirected because the session can't be persisted.
  sharedExtensions:
    extauth:
      enabled: true
    ratelimiter:
      enabled: true
    extCache:
      enabled: true
  rawConfig:
    config:
      tracing:
        otlpProtocol: grpc
        otlpEndpoint: http://solo-enterprise-telemetry-collector.${AGW_NAMESPACE}.svc.cluster.local:4317
        randomSampling: 'true'
        fields:
          add:
            jwt: 'jwt'
      metrics:
        fields:
          add:
            user_id: 'request.headers["x-user-id"]'
      logging:
        fields:
          add:
            jwt.all: 'jwt'
        format: json
EOF

###############################################################################
# 4. Bind the params to the GatewayClass via the controller chart
#    The controller's GatewayClass uses the helm value
#    gatewayClassParametersRefs.<class-name> to know which params resource to
#    consume. Adding it requires a helm upgrade + controller restart.
###############################################################################
log "Binding params to GatewayClass via helm upgrade of enterprise-agentgateway"

${HELM} upgrade enterprise-agentgateway "${AGW_CHART}" \
  --version "${AGW_CHART_VERSION}" \
  --namespace "${AGW_NAMESPACE}" \
  --reuse-values \
  --set 'gatewayClassParametersRefs.enterprise-agentgateway.group=enterpriseagentgateway.solo.io' \
  --set 'gatewayClassParametersRefs.enterprise-agentgateway.kind=EnterpriseAgentgatewayParameters' \
  --set 'gatewayClassParametersRefs.enterprise-agentgateway.name=agentgateway-config' \
  --set 'gatewayClassParametersRefs.enterprise-agentgateway.namespace='"${AGW_NAMESPACE}"

###############################################################################
# 5. Restart controller + data plane so the binding takes effect
#    The controller restart causes the GatewayClass.spec.parametersRef to
#    populate. The data plane restart causes the rendered gateway ConfigMap
#    to include the new tracing config.
###############################################################################
log "Restarting AGW controller + data plane"

${KC} -n "${AGW_NAMESPACE}" rollout restart deployment enterprise-agentgateway
${KC} -n "${AGW_NAMESPACE}" rollout status deployment enterprise-agentgateway --timeout=120s

${KC} -n "${AGW_NAMESPACE}" rollout restart deployment agentgateway-hub
${KC} -n "${AGW_NAMESPACE}" rollout status deployment agentgateway-hub --timeout=120s

###############################################################################
# 6. Wait for the UI pod, restart so DB migration runs cleanly
#    On first install the ClickHouse may not be ready before the UI's
#    schema-migration init container runs. A restart re-runs migration after
#    ClickHouse is up.
###############################################################################
log "Waiting for solo-enterprise-ui to be Ready, then restarting for clean migration"

${KC} -n "${AGW_NAMESPACE}" wait pod -l app=solo-enterprise-ui --for=condition=Ready --timeout=300s
${KC} -n "${AGW_NAMESPACE}" rollout restart deployment solo-enterprise-ui
${KC} -n "${AGW_NAMESPACE}" rollout status deployment solo-enterprise-ui --timeout=180s

# Restart the OTel collector too so it retries any failed ClickHouse exports
# from before the database migration completed.
${KC} -n "${AGW_NAMESPACE}" rollout restart statefulset solo-enterprise-telemetry-collector
${KC} -n "${AGW_NAMESPACE}" rollout status statefulset solo-enterprise-telemetry-collector --timeout=120s

###############################################################################
# 7. Summary
###############################################################################
log "AGW Enterprise management UI installed and wired"

echo ""
echo "Components running:"
${KC} -n "${AGW_NAMESPACE}" get pod -l 'app in (solo-enterprise-ui,solo-enterprise-telemetry-collector)' \
  -o custom-columns='NAME:.metadata.name,STATUS:.status.phase,READY:.status.containerStatuses[*].ready'
echo ""
echo "Access:"
echo "  ${KC} -n ${AGW_NAMESPACE} port-forward svc/solo-enterprise-ui 4000:80"
echo "  open http://localhost:4000"
echo ""
echo "Send some traffic (e.g. ./demo/send-traffic.sh) and refresh the UI to see"
echo "traces, sessions, and per-agent token metrics populate."
